# Generated by Django 3.2.9 on 2022-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appstudnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
